# Generated by Django 3.0.8 on 2020-09-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userctl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='accounnt',
            new_name='account',
        ),
    ]
