# Generated by Django 3.0.8 on 2020-09-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userctl', '0002_auto_20200918_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='phone',
        ),
    ]
