# Generated by Django 3.0.8 on 2020-11-18 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userctl.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userctl', '0003_remove_userinformation_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=userctl.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
