# Generated by Django 3.0.8 on 2020-11-24 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctl', '0004_auto_20201118_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
