# Generated by Django 3.0.8 on 2020-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctl', '0005_userinformation_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(choices=[('男生', 'Male'), ('女生', 'Female'), ('匿性', 'Unknow')], default='匿性', max_length=2),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='account',
            field=models.CharField(help_text='帳戶', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='fullname',
            field=models.CharField(help_text='小名或全名', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='password2',
            field=models.CharField(help_text='密碼驗證', max_length=50, null=True),
        ),
    ]
