# Generated by Django 3.0.8 on 2020-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userctl', '0006_auto_20201125_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='account',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='password2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(choices=[('Male', '男生'), ('Female', '女生'), ('Unknow', '匿性')], default='Unknow', max_length=10),
        ),
    ]
