# Generated by Django 3.2.6 on 2021-09-01 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_control.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50, null=True)),
                ('fullname', models.CharField(max_length=30)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('Male', '男生'), ('Female', '女生'), ('Unknow', '匿性')], default='Unknow', max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to=user_control.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
